### PR TITLE
Add Indonesian translation

### PR DESCRIPTION
**Pull request by lakuapik**
I look at the code, there is no Indonesian translation yet. So i've added Indonesian translation, also updated the README.

I know maybe its not one hundred percent correct, but i'm happy helping this #25

### CODE REVIEW

**Comment by lakuapik** [comment]
Yay.. 😁

Thanks @zrrrzzt, i run 
```bash 
$ npm run standar-fix
``` 

and it seems `oll korrect`.

**Comment by zrrrzzt** [comment]
Cool!

Merged @lakuapik I'll release it to npm later today

**Comment by maccyber** [comment]
In prod @ https://bigfive-test.com/test/id

**Comment by lakuapik** [comment]
Thank you @maccyber @zrrrzzt for accepting my PR and deploy it to prod :smiley:

**Pull request merged**
